ci(travis): Update script to enforce size threshold of image. (#3)
* docs(readme): Add Travis CI badge to README.

* ci(travis): Skip the install step and use node_js as the language.

* ci(travis): Update script to enforce size threshold of image.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,7 +7,19 @@ install: true
 
 language: node_js
 
-script: docker images
+script:
+- |
+  DOCKER_SIZE_STRING="$(docker images beeglercorp --format {{.Size}})"
+  DOCKER_SIZE_NUMBER=${DOCKER_SIZE_STRING%MB}
+
+  echo $DOCKER_SIZE_STRING
+  if [ 45 -gt $DOCKER_SIZE_NUMBER ]; then
+    echo "Ok"
+    exit 0
+  else
+    echo "Fail"
+    exit 1
+  fi
 
 services:
   - docker
